#!/bin/bash

. "${0%/*}/ml_env"

export ML_BUILD_MODEL="${1}"
export ML_DEPLOY_MODE="${2}"

. "${ML_BIN}/lib/ml_common"

log info "Call ml_card_deploy ${ML_CARD_DEVICE} ${ML_DEPLOY_MODE}"

sudo ${ML_BIN}/ml_card_deploy "${ML_BUILD_MODEL}" "${ML_DEPLOY_MODE}"|| log error "Unable to deploy!"

log info "done."
